#pragma once

#include <stdint.h>

#define SYSCALL_EXIT 0
#define SYSCALL_READ_FILE 1
#define SYSCALL_WRITE_FILE 2
#define SYSCALL_CREATE_FILE 3
#define SYSCALL_DELETE_FILE 4
#define SYSCALL_CREATE_DIR 5
#define SYSCALL_GET_PPID 6
#define SYSCALL_READ_SECTORS 7
#define SYSCALL_WRITE_SECTORS 8
#define SYSCALL_LIST_DIR 9
#define SYSCALL_GET_FILE_SIZE 10
#define SYSCALL_FORK 11
#define SYSCALL_EXECUTE 12
#define SYSCALL_GET_TIME 13
#define SYSCALL_GET_PID 14
#define SYSCALL_GET_UPTIME 15
#define SYSCALL_DELAY 16
#define SYSCALL_READ_CONSOLE 17
#define SYSCALL_WRITE_CONSOLE 18
#define SYSCALL_ALLOC_PAGE 19
#define SYSCALL_FREE_PAGE 20
#define SYSCALL_GETENV 21
#define SYSCALL_REBOOT 22
#define SYSCALL_VPRINTF 23

uint64_t syscall(uint64_t syscall_number, uint64_t arg1, uint64_t arg2, uint64_t arg3, uint64_t arg4, uint64_t arg5);
