#pragma once

#include <stdint.h>

#define SYSCALL_EXIT 0
#define SYSCALL_READ_FILE 1
#define SYSCALL_WRITE_FILE 2
#define SYSCALL_CREATE_FILE 3
#define SYSCALL_DELETE_FILE 4
#define SYSCALL_CREATE_DIR 5
#define SYSCALL_GET_PPID 6
#define SYSCALL_READ_SECTORS 7
#define SYSCALL_WRITE_SECTORS 8
#define SYSCALL_LIST_DIR 9
#define SYSCALL_GET_FILE_SIZE 10
#define SYSCALL_FORK 11
#define SYSCALL_EXECUTE 12
#define SYSCALL_GET_TIME 13
#define SYSCALL_GET_PID 14
#define SYSCALL_GET_UPTIME 15
#define SYSCALL_DELAY 16
#define SYSCALL_READ_CONSOLE 17
#define SYSCALL_WRITE_CONSOLE 18
#define SYSCALL_ALLOC_PAGE 19
#define SYSCALL_FREE_PAGE 20
#define SYSCALL_GETENV 21
#define SYSCALL_REBOOT 22
#define SYSCALL_VPRINTF 23
#define SYSCALL_CHDIR 24
#define SYSCALL_GETCWD 25
#define SYSCALL_FILE_EXISTS 26
#define SYSCALL_IS_DIRECTORY 27
#define SYSCALL_SEND_UDP 28
#define SYSCALL_LISTEN_UDP 29
#define SYSCALL_PING 30
#define SYSCALL_GET_MAC 31
#define SYSCALL_GET_IP 32
#define SYSCALL_ADD_ROUTE 33
#define SYSCALL_REMOVE_ROUTE 34
#define SYSCALL_SETUP_AUTOMATIC_ROUTING 35
#define SYSCALL_CONFIG_DHCP 36
#define SYSCALL_CONFIG_STATIC 37
#define SYSCALL_STOP_UDP_LISTEN 38

uint64_t syscall(uint64_t syscall_number, uint64_t arg1, uint64_t arg2, uint64_t arg3, uint64_t arg4, uint64_t arg5);
